<#
setup-gcp.ps1

This script automates local GCP setup for development:
- checks for gcloud
- sets project
- enables Vertex AI and BigQuery APIs
- creates a service account and grants roles
- creates a key file under backend/credentials/
- optionally writes a `backend/.env` template

Run from PowerShell (developer machine) after installing Google Cloud SDK and logging in.
#>

Set-StrictMode -Version Latest

function ExitWithError($msg) {
    Write-Host "ERROR: $msg" -ForegroundColor Red
    exit 1
}

if (-not (Get-Command gcloud -ErrorAction SilentlyContinue)) {
    ExitWithError "gcloud CLI not found. Install Google Cloud SDK: https://cloud.google.com/sdk/docs/install"
}

Write-Host "This script will enable required GCP APIs, create a service account, and produce a key file for local development." -ForegroundColor Cyan

$projectId = Read-Host "Enter your GCP project ID"
if (-not $projectId) { ExitWithError "Project ID is required." }

Write-Host "Setting gcloud project to $projectId" -ForegroundColor Green
gcloud config set project $projectId | Out-Null

$apis = @(
    'aiplatform.googleapis.com',
    'bigquery.googleapis.com',
    'iam.googleapis.com',
    'cloudresourcemanager.googleapis.com'
)

Write-Host "Enabling APIs: $($apis -join ', ')" -ForegroundColor Green
gcloud services enable $($apis -join ' ') --project $projectId

$saName = Read-Host "Enter service account name (default: orbyte-sa)" -ErrorAction SilentlyContinue
if (-not $saName) { $saName = 'orbyte-sa' }

$saDisplay = 'Orbyte local dev service account'
$saEmail = "$saName@$projectId.iam.gserviceaccount.com"

Write-Host "Creating service account $saName (if it does not already exist)" -ForegroundColor Green
try {
    gcloud iam service-accounts create $saName --display-name "$saDisplay" --project $projectId | Out-Null
} catch {
    Write-Host "Service account may already exist, continuing..." -ForegroundColor Yellow
}

$roles = @(
    'roles/bigquery.dataViewer',
    'roles/bigquery.jobUser',
    'roles/aiplatform.user'
)

Write-Host "Granting roles to $saEmail" -ForegroundColor Green
foreach ($role in $roles) {
    Write-Host "  - $role"
    gcloud projects add-iam-policy-binding $projectId --member="serviceAccount:$saEmail" --role="$role" --quiet | Out-Null
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Definition
$credDir = Join-Path $scriptRoot "..\credentials"
if (-not (Test-Path $credDir)) { New-Item -Path $credDir -ItemType Directory -Force | Out-Null }

$keyPath = Join-Path $credDir "$saName-key.json"
Write-Host "Creating service account key at: $keyPath" -ForegroundColor Green
gcloud iam service-accounts keys create "$keyPath" --iam-account $saEmail --project $projectId

$absKey = (Resolve-Path $keyPath).Path

Write-Host "\nKey created at: $absKey" -ForegroundColor Cyan
Write-Host "Important: Do NOT commit this key to source control. The script added backend/credentials/ to .gitignore." -ForegroundColor Yellow

Write-Host "\nOptions:" -ForegroundColor Cyan
Write-Host "1) Set environment variable for current PowerShell session:" -NoNewline; Write-Host " `$env:GOOGLE_APPLICATION_CREDENTIALS = '$absKey'" -ForegroundColor Green
Write-Host "2) Persist environment variable for future sessions (you may need to re-open the shell):" -NoNewline; Write-Host " setx GOOGLE_APPLICATION_CREDENTIALS '$absKey'" -ForegroundColor Green

$writeEnv = Read-Host "Would you like the script to create/update backend/.env with the values? (y/N)"
if ($writeEnv -and $writeEnv.ToLower().StartsWith('y')) {
    $envFile = Join-Path $scriptRoot "..\..\backend\.env"
    $content = @()
    $content += "# Generated by setup-gcp.ps1"
    $content += "GOOGLE_APPLICATION_CREDENTIALS=$absKey"
    $content += "GCP_PROJECT_ID=$projectId"
    $content += "GCP_LOCATION=us-central1"
    $content += "VERTEX_MODEL_NAME=gemini-2.0-flash-exp"
    $content += "ORBYTE_USE_MOCK_AI=false"

    Write-Host "Writing environment file to $envFile" -ForegroundColor Green
    $content | Out-File -FilePath $envFile -Encoding UTF8 -Force
    Write-Host "Created/updated backend/.env (do not commit)" -ForegroundColor Yellow
}

Write-Host "\nDone. Verify Vertex AI API status using the console or the commands shown in the README." -ForegroundColor Cyan

Write-Host "To check Vertex AI is enabled now (PowerShell):" -ForegroundColor Cyan
Write-Host "  $projectId = '<your-project-id>'" -ForegroundColor Green
Write-Host "  $enabled = gcloud services list --enabled --project $projectId --filter='NAME:aiplatform.googleapis.com' --format='value(config.name)'" -ForegroundColor Green
Write-Host "  if ($enabled) { Write-Host 'Vertex AI API is ENABLED' } else { Write-Host 'Vertex AI API is NOT enabled' }" -ForegroundColor Green

Write-Host "Also you can visit: https://console.cloud.google.com/apis/library/aiplatform.googleapis.com?project=$projectId" -ForegroundColor Cyan
